version: '3.4' 

services:
  
  BasketDb:
    image: postgres

  CatalogDb:
    image: postgres

  DistributedCache:
      image: redis

  Catalog.API:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket: